updating to v3.9

diff --git a/core/python3AiActionLoop/Dockerfile b/core/python3AiActionLoop/Dockerfile
--- a/core/python3AiActionLoop/Dockerfile
+++ b/core/python3AiActionLoop/Dockerfile
@@ -37,7 +37,7 @@ RUN curl -sL \
 FROM tensorflow/tensorflow:1.15.2-py3-jupyter
 
 # select the builder to use
-ARG GO_PROXY_BUILD_FROM=release
+ARG GO_PROXY_BUILD_FROM=source
 
 RUN apt-get update && apt-get upgrade -y && apt-get install -y \
             curl \
@@ -53,7 +53,11 @@ RUN apt-get update && apt-get upgrade -y && apt-get install -y \
             && rm -rf /var/lib/apt/lists/*
 
 # PyTorch
-RUN pip3 install torch torchvision
+# persistent as it fails often
+RUN while ! pip list | grep torch ;\
+    do pip install torch ; done ;\
+    while ! pip list | grep torchvision ;\
+    do pip install torchvision ; done
 
 # rclone
 RUN curl -L https://downloads.rclone.org/rclone-current-linux-amd64.deb -o rclone.deb \
